### ISSUE TITLE
Rupta crashed when trying to analyze Substrate Node Template

### ISSUE THREAD

**Issue by Endericedragon** [rustanlys/rupta#3]
I am using Rupta to analyze [an older version of Substrate Node Template](https://github.com/Endericedragon/substrate-node-template-copy). However, when I run rupta, it crashed and I received some error message. Here is the code I run:

```sh
export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
cargo-pta pta --release -- --entry-func main --dump-call-graph cg.dot --dump-pts pts.txt
```

And here is the error message:

```
     Running `/home/endericedragon/.cargo/bin/cargo-pta /home/endericedragon/.rustup/toolchains/nightly-2024-02-03-x86_64-unknown-linux-gnu/bin/rustc --crate-name node_template --edition=2021 node/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=187 --crate-type bin --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' -C metadata=4682dc25484d0090 -C extra-filename=-4682dc25484d0090 --out-dir /home/endericedragon/repos/substrate-node-template-copy/target/release/deps -C strip=debuginfo -L dependency=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps --extern clap=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libclap-b93f4a5060d339df.rmeta --extern frame_benchmarking=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_benchmarking-526d8e14c4d88e2e.rmeta --extern frame_benchmarking_cli=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_benchmarking_cli-b0942ae1ec54d3e8.rmeta --extern frame_system=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_system-9a97457edb5aa3a4.rmeta --extern futures=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libfutures-0657d23efe7ddbc7.rmeta --extern jsonrpsee=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libjsonrpsee-df2a08305033a2fb.rmeta --extern node_template=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libnode_template-e97827ef26b660bc.rmeta --extern node_template_runtime=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libnode_template_runtime-1258c3169e5d4206.rmeta --extern pallet_transaction_payment=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libpallet_transaction_payment-7f9d93bc4da80d0e.rmeta --extern pallet_transaction_payment_rpc=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libpallet_transaction_payment_rpc-7ba4d8a483987661.rmeta --extern sc_basic_authorship=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_basic_authorship-9acc44af58916c60.rmeta --extern sc_cli=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_cli-a02aee59ed8d3eeb.rmeta --extern sc_client_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_client_api-bf33d32df8d1e8f3.rmeta --extern sc_consensus=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus-d8944f75789afe34.rmeta --extern sc_consensus_aura=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus_aura-ddfd4fffd11bb188.rmeta --extern sc_consensus_grandpa=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus_grandpa-9c1a2d7e3fcf2dce.rmeta --extern sc_executor=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_executor-8bdd6a66c1006da3.rmeta --extern sc_network=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_network-dd7c50b678478a0d.rmeta --extern sc_offchain=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_offchain-f0331688b1853944.rmeta --extern sc_rpc_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_rpc_api-c5f1dbb7fabbd3bf.rmeta --extern sc_service=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_service-12918ea595ec50e0.rmeta --extern sc_statement_store=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_statement_store-fa15dcd2ee60dec3.rmeta --extern sc_telemetry=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_telemetry-5b3143f9679b5e09.rmeta --extern sc_transaction_pool=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_transaction_pool-af929fc47f0abafb.rmeta --extern sc_transaction_pool_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_transaction_pool_api-b42c7e527965c80a.rmeta --extern sp_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_api-66e2497628ee7c57.rmeta --extern sp_block_builder=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_block_builder-27cafc9a59eb8b9b.rmeta --extern sp_blockchain=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_blockchain-923b376467cd4bd1.rmeta --extern sp_consensus_aura=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_consensus_aura-4dd36008b93c10bc.rmeta --extern sp_consensus_grandpa=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_consensus_grandpa-ee34c37acd541271.rmeta --extern sp_core=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_core-ea394a10482b4e47.rmeta --extern sp_inherents=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_inherents-84c21e0aa3dfc415.rmeta --extern sp_io=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_io-bbf8b7d8262ef267.rmeta --extern sp_keyring=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_keyring-6d9a9853bbc131bd.rmeta --extern sp_runtime=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_runtime-9f88f8738fec0221.rmeta --extern sp_timestamp=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_timestamp-8c1e40de05adcba1.rmeta --extern substrate_frame_rpc_system=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsubstrate_frame_rpc_system-61941b511c4ecee6.rmeta -Z always_encode_mir -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/secp256k1-sys-30adedace81f3255/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/psm-797561feeccef94d/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/zstd-sys-182dad89d171d540/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/wasmtime-runtime-0dbad21a8f6087dc/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/blake3-b69f35ae3c08cdba/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/blake3-b69f35ae3c08cdba/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/librocksdb-sys-23bebd4cf1e1856b/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/librocksdb-sys-23bebd4cf1e1856b/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/tikv-jemalloc-sys-02b951e3579e8d7c/out/build/lib -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/lz4-sys-8a4a456edb69adf8/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/ring-9b05b8e8b9375404/out`
thread 'rustc' panicked at src/pta/propagator/propagator.rs:482:17:
internal error: entered unreachable code: Expected second type argument to be a tuple type
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
note: no errors encountered even though `span_delayed_bug` issued

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: cannot relate consts of different types (a=1_usize, b=?0c: bool)
  |
  = note: delayed at compiler/rustc_infer/src/infer/relate/combine.rs:183:32 - disabled backtrace

thread 'rustc' panicked at compiler/rustc_errors/src/lib.rs:1462:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f98eb38bd16 - std::backtrace_rs::backtrace::libunwind::trace::he544685250360e22
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f98eb38bd16 - std::backtrace_rs::backtrace::trace_unsynchronized::h664adef12633380a
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f98eb38bd16 - std::sys_common::backtrace::_print_fmt::hba7ee045aeee07b0
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f98eb38bd16 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc80b7ff177a688f2
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f98eb3de770 - core::fmt::rt::Argument::fmt::h605309ab4829b6b5
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/core/src/fmt/rt.rs:142:9
   5:     0x7f98eb3de770 - core::fmt::write::h5f24f526de99e105
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f98eb37f61f - std::io::Write::write_fmt::h711c920f97cd3d8c
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/io/mod.rs:1846:15
   7:     0x7f98eb38baf4 - std::sys_common::backtrace::_print::ha279702af2871260
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f98eb38baf4 - std::sys_common::backtrace::print::hc1f3820f405abdd3
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f98eb38e887 - std::panicking::default_hook::{{closure}}::h5058841d19c78172
  10:     0x7f98eb38e5e9 - std::panicking::default_hook::h60a42497ec033f97
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/panicking.rs:292:9
  11:     0x7f98eb38ee48 - std::panicking::rust_panic_with_hook::h294fbe090fe44fa4
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/panicking.rs:781:13
  12:     0x7f98ee1693e8 - std[4337b1e3d1c66af6]::panicking::begin_panic::<rustc_errors[37e82e04e08bc148]::DelayedBugPanic>::{closure#0}
  13:     0x7f98ee165ab6 - std[4337b1e3d1c66af6]::sys_common::backtrace::__rust_end_short_backtrace::<std[4337b1e3d1c66af6]::panicking::begin_panic<rustc_errors[37e82e04e08bc148]::DelayedBugPanic>::{closure#0}, !>
  14:     0x7f98ee160d16 - std[4337b1e3d1c66af6]::panicking::begin_panic::<rustc_errors[37e82e04e08bc148]::DelayedBugPanic>
  15:     0x7f98eff6d775 - <rustc_errors[37e82e04e08bc148]::DiagCtxtInner>::flush_delayed
  16:     0x7f98eff6d4a5 - <rustc_errors[37e82e04e08bc148]::DiagCtxtInner as core[cc6cd760d986f799]::ops::drop::Drop>::drop
  17:     0x7f98eff6c738 - core[cc6cd760d986f799]::ptr::drop_in_place::<rustc_errors[37e82e04e08bc148]::DiagCtxt>
  18:     0x7f98f01db797 - core[cc6cd760d986f799]::ptr::drop_in_place::<rustc_session[5dfdd5332aa7c7e]::parse::ParseSess>
  19:     0x7f98f01dbd37 - core[cc6cd760d986f799]::ptr::drop_in_place::<rustc_interface[e57535df52585ed5]::interface::Compiler>
  20:     0x7f98f011aa75 - rustc_interface[e57535df52585ed5]::interface::run_compiler::<core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>, rustc_driver_impl[e51f6499da6a94b9]::run_compiler::{closure#0}>::{closure#0}
  21:     0x7f98efdada86 - std[4337b1e3d1c66af6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e57535df52585ed5]::util::run_in_thread_with_globals<rustc_interface[e57535df52585ed5]::util::run_in_thread_pool_with_globals<rustc_interface[e57535df52585ed5]::interface::run_compiler<core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>, rustc_driver_impl[e51f6499da6a94b9]::run_compiler::{closure#0}>::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>
  22:     0x7f98efdad8b3 - <<std[4337b1e3d1c66af6]::thread::Builder>::spawn_unchecked_<rustc_interface[e57535df52585ed5]::util::run_in_thread_with_globals<rustc_interface[e57535df52585ed5]::util::run_in_thread_pool_with_globals<rustc_interface[e57535df52585ed5]::interface::run_compiler<core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>, rustc_driver_impl[e51f6499da6a94b9]::run_compiler::{closure#0}>::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[cc6cd760d986f799]::result::Result<(), rustc_span[ecf473d7733698d2]::ErrorGuaranteed>>::{closure#1} as core[cc6cd760d986f799]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  23:     0x7f98eb398675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc4b9a6efba849e51
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/alloc/src/boxed.rs:2015:9
  24:     0x7f98eb398675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc525ee5ac423ddcd
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/alloc/src/boxed.rs:2015:9
  25:     0x7f98eb398675 - std::sys::pal::unix::thread::Thread::new::thread_start::h31b81f67226864c0
                               at /rustc/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/library/std/src/sys/pal/unix/thread.rs:108:17
  26:     0x7f98eb144ac3 - <unknown>
  27:     0x7f98eb1d6850 - <unknown>
  28:                0x0 - <unknown>
thread 'rustc' panicked at library/core/src/panicking.rs:163:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
error: could not compile `node-template` (bin "node-template")

Caused by:
  process didn't exit successfully: `/home/endericedragon/.cargo/bin/cargo-pta /home/endericedragon/.rustup/toolchains/nightly-2024-02-03-x86_64-unknown-linux-gnu/bin/rustc --crate-name node_template --edition=2021 node/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=187 --crate-type bin --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' -C metadata=4682dc25484d0090 -C extra-filename=-4682dc25484d0090 --out-dir /home/endericedragon/repos/substrate-node-template-copy/target/release/deps -C strip=debuginfo -L dependency=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps --extern clap=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libclap-b93f4a5060d339df.rmeta --extern frame_benchmarking=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_benchmarking-526d8e14c4d88e2e.rmeta --extern frame_benchmarking_cli=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_benchmarking_cli-b0942ae1ec54d3e8.rmeta --extern frame_system=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libframe_system-9a97457edb5aa3a4.rmeta --extern futures=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libfutures-0657d23efe7ddbc7.rmeta --extern jsonrpsee=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libjsonrpsee-df2a08305033a2fb.rmeta --extern node_template=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libnode_template-e97827ef26b660bc.rmeta --extern node_template_runtime=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libnode_template_runtime-1258c3169e5d4206.rmeta --extern pallet_transaction_payment=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libpallet_transaction_payment-7f9d93bc4da80d0e.rmeta --extern pallet_transaction_payment_rpc=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libpallet_transaction_payment_rpc-7ba4d8a483987661.rmeta --extern sc_basic_authorship=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_basic_authorship-9acc44af58916c60.rmeta --extern sc_cli=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_cli-a02aee59ed8d3eeb.rmeta --extern sc_client_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_client_api-bf33d32df8d1e8f3.rmeta --extern sc_consensus=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus-d8944f75789afe34.rmeta --extern sc_consensus_aura=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus_aura-ddfd4fffd11bb188.rmeta --extern sc_consensus_grandpa=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_consensus_grandpa-9c1a2d7e3fcf2dce.rmeta --extern sc_executor=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_executor-8bdd6a66c1006da3.rmeta --extern sc_network=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_network-dd7c50b678478a0d.rmeta --extern sc_offchain=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_offchain-f0331688b1853944.rmeta --extern sc_rpc_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_rpc_api-c5f1dbb7fabbd3bf.rmeta --extern sc_service=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_service-12918ea595ec50e0.rmeta --extern sc_statement_store=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_statement_store-fa15dcd2ee60dec3.rmeta --extern sc_telemetry=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_telemetry-5b3143f9679b5e09.rmeta --extern sc_transaction_pool=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_transaction_pool-af929fc47f0abafb.rmeta --extern sc_transaction_pool_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsc_transaction_pool_api-b42c7e527965c80a.rmeta --extern sp_api=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_api-66e2497628ee7c57.rmeta --extern sp_block_builder=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_block_builder-27cafc9a59eb8b9b.rmeta --extern sp_blockchain=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_blockchain-923b376467cd4bd1.rmeta --extern sp_consensus_aura=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_consensus_aura-4dd36008b93c10bc.rmeta --extern sp_consensus_grandpa=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_consensus_grandpa-ee34c37acd541271.rmeta --extern sp_core=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_core-ea394a10482b4e47.rmeta --extern sp_inherents=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_inherents-84c21e0aa3dfc415.rmeta --extern sp_io=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_io-bbf8b7d8262ef267.rmeta --extern sp_keyring=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_keyring-6d9a9853bbc131bd.rmeta --extern sp_runtime=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_runtime-9f88f8738fec0221.rmeta --extern sp_timestamp=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsp_timestamp-8c1e40de05adcba1.rmeta --extern substrate_frame_rpc_system=/home/endericedragon/repos/substrate-node-template-copy/target/release/deps/libsubstrate_frame_rpc_system-61941b511c4ecee6.rmeta -Z always_encode_mir -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/secp256k1-sys-30adedace81f3255/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/psm-797561feeccef94d/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/zstd-sys-182dad89d171d540/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/wasmtime-runtime-0dbad21a8f6087dc/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/blake3-b69f35ae3c08cdba/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/blake3-b69f35ae3c08cdba/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/librocksdb-sys-23bebd4cf1e1856b/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/librocksdb-sys-23bebd4cf1e1856b/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/tikv-jemalloc-sys-02b951e3579e8d7c/out/build/lib -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/lz4-sys-8a4a456edb69adf8/out -L native=/home/endericedragon/repos/substrate-node-template-copy/target/release/build/ring-9b05b8e8b9375404/out` (exit status: 255)
```

I am totally confused and I do not know where things go wrong. If more information is needed or reproducing this issue is unsuccessful, please let me know.

**Comment by LeeeWee** [comment]
Thanks for reporting the issue. The problem was caused by an error in processing the arguments for dynamic function trait calls. We have now fixed this in the latest commit.
